spring:
  application:
    # 应用的名字
    name: eureka-client-article-service
  security:
    user:
      name: kevin
      password: 123456
server:
  # Eureka服务提供者端口号
  port: 8082
eureka:
  instance:
    hostname: localhost
    # 采用IP注册
    prefer-ip-address: true
    # 实例id格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:14001/eureka/
