spring:
  application:
    # 应用的名字
    name: eureka-server
  security:
    user:
      name: kevin
      password: 123456
  profiles:
    active: slaveone
#server:
#  # Eureka注册中心端口号
#  port: 14001
eureka:
  instance:
    hostname: eurekaslaveone
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
