spring:
  application:
    # 应用的名字
    name: ribbon-native-demo
  security:
    user:
      name: kevin
      password: 123456
server:
  # Eureka服务提供者端口号
  port: 8083
eureka:
  instance:
    # 发送心跳的时间
    lease-renewal-interval-in-seconds: 5
    # 等待下一个心跳的时间
    lease-expiration-duration-in-seconds: 5
    hostname: localhost
    # 采用IP注册
    prefer-ip-address: true
    # 实例id格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    # 健康检查
    healthcheck:
      enabled: true
    # 服务路径
    service-url:
      defaultZone: "http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:14001/eureka/,/
      http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:14002/eureka/"
ribbon:
  eager-load:
    enabled: true
    clients: ribbon-native-demo
  maxAutoRetries: 1
  maxAutoRetriesNextServer: 3
  okToRetryOnAllOperations: true
  retryablesStatusCodes: 500,404,502
# 声明式REST客户端
feign:
  # 开启压缩
  compression:
    # 请求
    request:
      enabled: true
      # 压缩类型
      mime-types:
        - text/xml
        - application/xml
        - application/json
      # 最小容量
      min-request-size: 2048
    # 响应
    response:
      enabled: true
  # 客户端
  client:
    # 配置
    config:
      # Eureka服务
      eureka-client:
        # 日志显示内容
        loggerLevel: FULL
        # 连接超时时间
        connectTimeout: 5000
        # 读取超时时间
        readTimeout: 5000
logging:
  level:
    com.ky.kevin.feign.UserRemoteClient: DEBUG
